/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CountryBumpCombination: typeof import('./components/countryBump/countryBumpCombination.vue')['default']
    CountryBumpItem: typeof import('./components/countryBump/countryBumpItem.vue')['default']
    CountryBumpLine: typeof import('./components/countryBump/countryBumpLine.vue')['default']
    FlagWall: typeof import('./components/FlagWall.vue')['default']
    GpcNearestTokenDistanceForm: typeof import('./components/gpc/gpcNearestTokenDistanceForm.vue')['default']
    GpcNearestTokenDistanceFormABXY: typeof import('./components/gpc/gpcNearestTokenDistanceFormABXY.vue')['default']
    GpcNearestTokenDistanceFormBilateral: typeof import('./components/gpc/gpcNearestTokenDistanceFormBilateral.vue')['default']
    KnowledgeUnitSquare: typeof import('./components/gpc/knowledgeUnitSquare.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheCountrySelect: typeof import('./components/TheCountrySelect.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    ThePaperSubjectSelect: typeof import('./components/ThePaperSubjectSelect.vue')['default']
  }
}
